// rostrum-gen — regenerates Sources/Rostrum/Schema/GeneratedSchema.swift from
// Tools/tables/oxml-schema.json (which is itself mechanically extracted from
// python-pptx by Tools/extract-schema.py; see Tools/README.md).
//
// Zero dependencies by design: Foundation + JSONSerialization only.
//
// Usage: swift run rostrum-gen Tools/tables/oxml-schema.json [output.swift]

import Foundation

func die(_ message: String) -> Never {
    FileHandle.standardError.write(Data("rostrum-gen: FATAL: \(message)\n".utf8))
    exit(1)
}

// MARK: - Arguments

let arguments = CommandLine.arguments
guard arguments.count >= 2 else {
    die("usage: rostrum-gen <oxml-schema.json> [GeneratedSchema.swift]")
}
let jsonPath = arguments[1]
let outputPath = arguments.count > 2
    ? arguments[2]
    : "Sources/Rostrum/Schema/GeneratedSchema.swift"

// MARK: - Load JSON

guard let jsonData = FileManager.default.contents(atPath: jsonPath) else {
    die("cannot read \(jsonPath)")
}
guard
    let root = try? JSONSerialization.jsonObject(with: jsonData) as? [String: Any],
    let classes = root["classes"] as? [String: [String: Any]],
    let tagMap = root["tags"] as? [String: String]
else {
    die("\(jsonPath) is not the expected oxml-schema JSON shape")
}

// MARK: - Build tables

/// parent tag → child tag → successor tags (declared order preserved).
var childSuccessors: [String: [String: [String]]] = [:]
/// element tag → XML attribute name → default value string.
var attributeDefaults: [String: [String: String]] = [:]
/// element tag → required XML attribute names (sorted).
var requiredAttributes: [String: [String]] = [:]
/// every distinct element tag the schema knows about.
var elementTags: Set<String> = Set(tagMap.keys)

for (tag, className) in tagMap {
    guard let cls = classes[className] else {
        die("tag \(tag) maps to unknown class \(className)")
    }
    let attributes = cls["attributes"] as? [String: [String: Any]] ?? [:]
    let children = cls["children"] as? [String: [String: Any]] ?? [:]
    let choiceGroups = cls["choiceGroups"] as? [String: [String: Any]] ?? [:]

    var required: [String] = []
    for (attrName, attr) in attributes {
        if attr["required"] as? Bool == true {
            required.append(attrName)
        }
        if let defaultValue = attr["default"] as? String {
            attributeDefaults[tag, default: [:]][attrName] = defaultValue
        }
    }
    if !required.isEmpty {
        requiredAttributes[tag] = required.sorted()
    }

    for (childTag, child) in children {
        elementTags.insert(childTag)
        guard let successors = child["successors"] as? [String] else {
            die("class \(className) child \(childTag) has no successors array")
        }
        elementTags.formUnion(successors)
        guard !successors.isEmpty else { continue }
        if childSuccessors[tag]?[childTag] != nil {
            die("duplicate successors entry for \(tag)/\(childTag)")
        }
        childSuccessors[tag, default: [:]][childTag] = successors
    }

    for (groupName, group) in choiceGroups {
        guard
            let choices = group["choices"] as? [String],
            let successors = group["successors"] as? [String]
        else {
            die("class \(className) choice group \(groupName) is malformed")
        }
        elementTags.formUnion(choices)
        elementTags.formUnion(successors)
        guard !successors.isEmpty else { continue }
        for choiceTag in choices {
            if childSuccessors[tag]?[choiceTag] != nil {
                die("duplicate successors entry for \(tag)/\(choiceTag)")
            }
            childSuccessors[tag, default: [:]][choiceTag] = successors
        }
    }
}

// MARK: - Emit Swift source (deterministic: every map sorted by key)

func quoted(_ s: String) -> String {
    var out = "\""
    for ch in s.unicodeScalars {
        switch ch {
        case "\"": out += "\\\""
        case "\\": out += "\\\\"
        default: out.unicodeScalars.append(ch)
        }
    }
    return out + "\""
}

func stringArray(_ values: [String]) -> String {
    "[" + values.map(quoted).joined(separator: ", ") + "]"
}

var out = ""
out += "// Generated by rostrum-gen from python-pptx oxml declarations. Do not edit.\n"
out += "//\n"
out += "// Regenerate with:\n"
out += "//   python3 Tools/extract-schema.py <python-pptx>/src/pptx\n"
out += "//   swift run rostrum-gen Tools/tables/oxml-schema.json\n"
out += "\n"
out += "/// Schema knowledge mechanically extracted from python-pptx's xmlchemy\n"
out += "/// descriptor declarations (`RequiredAttribute`, `ZeroOrOne(successors:)`,\n"
out += "/// `ZeroOrOneChoice`, …) and its `register_element_cls` tag registrations.\n"
out += "public enum OOXMLSchema {\n"

out += "\n"
out += "    /// Parent element tag → child tag → the tags that must follow that child\n"
out += "    /// in schema order. Insert a new child immediately before the first\n"
out += "    /// successor already present (else append). Only children with declared\n"
out += "    /// successors appear. Successor order is semantic — do not sort.\n"
out += "    public static let childSuccessors: [String: [String: [String]]] = [\n"
for parent in childSuccessors.keys.sorted() {
    out += "        \(quoted(parent)): [\n"
    let children = childSuccessors[parent]!
    for child in children.keys.sorted() {
        out += "            \(quoted(child)): \(stringArray(children[child]!)),\n"
    }
    out += "        ],\n"
}
out += "    ]\n"

out += "\n"
out += "    /// Element tag → XML attribute name → default value in XML lexical form.\n"
out += "    /// Reading an absent attribute yields the default; writing the default\n"
out += "    /// value elides the attribute. Only attributes with declared defaults\n"
out += "    /// appear.\n"
out += "    public static let attributeDefaults: [String: [String: String]] = [\n"
for tag in attributeDefaults.keys.sorted() {
    out += "        \(quoted(tag)): [\n"
    let attrs = attributeDefaults[tag]!
    for name in attrs.keys.sorted() {
        out += "            \(quoted(name)): \(quoted(attrs[name]!)),\n"
    }
    out += "        ],\n"
}
out += "    ]\n"

out += "\n"
out += "    /// Element tag → XML attribute names the schema requires on that element.\n"
out += "    public static let requiredAttributes: [String: [String]] = [\n"
for tag in requiredAttributes.keys.sorted() {
    out += "        \(quoted(tag)): \(stringArray(requiredAttributes[tag]!)),\n"
}
out += "    ]\n"

out += "\n"
out += "    /// Every distinct element tag known to the schema: registered element\n"
out += "    /// classes plus all declared child, choice-member and successor tags.\n"
out += "    public static let elementTags: [String] = [\n"
for tag in elementTags.sorted() {
    out += "        \(quoted(tag)),\n"
}
out += "    ]\n"

out += "}\n"

// MARK: - Write

let outputURL = URL(fileURLWithPath: outputPath)
do {
    try FileManager.default.createDirectory(
        at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
    try Data(out.utf8).write(to: outputURL)
} catch {
    die("cannot write \(outputPath): \(error)")
}

print(
    "rostrum-gen: \(childSuccessors.count) parents with successor lists, "
        + "\(attributeDefaults.count) tags with attribute defaults, "
        + "\(requiredAttributes.count) tags with required attributes, "
        + "\(elementTags.count) element tags -> \(outputPath)")
