import Foundation
import Rostrum

/// Offline recipes backed by concrete public library calls, not screenshots.
enum PlatformLabRecipes {
    static let catalog: [LibraryLabRecipe] = [
        .init(.imageOwners, title: "Image fill ownership", summary: "Follow theme, slide, layout and master image resources, then override a theme image with public fill APIs.", operations: ["Slides.importAll", "Shape.fill", "Shape.setFill", "Presentation.outline", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Four source pages preserve seven native image paints and their owning relationships. The canvas extends to 864 by 540 points without scaling any specimen. Complete source files are retained separately; whole-page identity is not claimed.", "Exact selected PNG bytes and finite image rectangles match captured references within .001 pt. This does not establish arbitrary crop, transform, interpolation or occlusion parity. The fifth page is a public override control outside the native numerical oracle."], inputs: [.alternative], alternativeLabel: "Suppress the public image with no fill"),
        .init(.layouts, title: "Layouts and placeholders", summary: "Compare cloned placeholders with a layout-bound canvas and inspect inherited geometry and master ordering.", operations: ["Presentation.layouts", "layout(type:)", "layout(named:)", "Slides.add(clonedFrom:)", "Presentation.titleSlide / bulletSlide (layout-bound builders)", "Shape.markAsPlaceholder", "Slide.effectiveFrame", "Presentation.slideMasters", "Presentation.theme"], inputs: [.text, .alternative], alternativeLabel: "Use title-and-content layout"),
        .init(.fontsAndFitting, title: "Fonts, shaping and fitting", summary: "Measure and fit text with a bundled licensed font, then embed and reopen it.", operations: ["FontLibrary.register", "FontLibrary.metrics(for:bold:italic:)", "TextMeasurer.width", "TextMeasurer.wrap", "TextShaper.shape", "TextFrame.fitText", "Presentation.embedFont", "Presentation.registerEmbeddedFonts"], limitations: ["Only the licensed regular DejaVu face is bundled; unavailable bold and italic faces are reported, never synthesized.", "Shaping supports a bounded script and positioning profile; diagnostics remain visible."], inputs: [.text, .sampleSize, .alternative], alternativeLabel: "Use a narrower fitting box"),
        .init(.paragraphLayout, title: "Paragraph spacing and justification", summary: "Compare justification, native wrapping boundaries, common Latin words, styled empty lines, explicit spacing with native vertical anchors, and glyph size and placement.", operations: ["Paragraph.alignment", "Paragraph.addRun", "Part.dom", "Part.markDirty", "XML.Element.children", "TextFrame.setAutoFit", "Shape.fitText", "TextFrame.fitText", "RichTextLayout.init", "RichTextLine.visibleWidth", "ShapeCollection.addTable", "TableCell.textFrame", "Presentation.embedFont", "Presentation.registerEmbeddedFonts", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Justification expands interior spaces for bounded left-to-right Latin text; the final paragraph line stays natural. Explicit line breaks can expand.", "Right-to-left and non-Latin justification, distributed and low justification remain diagnosed limitations. See the tab-stop demo for the bounded tab-aware profile.", "The sample body uses fixed English text and a bundled regular DejaVu face. Your text changes the title; sample size changes sentence count. Narrower columns also select the independently measured narrow boundary cases on slide 3. Boundary references cover single-scalar ASCII glyphs, left alignment and zero insets; slide 4 adds native officeZ wrapping and fixed-width mixed 18/12 pt runs. Slide 5 imports owned DrawingML specimens with consecutive breaks and trailing paragraph-end styles; the alternative selects 36 pt rather than 6 pt empty lines. Native marker baselines cover regular DejaVu Sans, top alignment and zero insets. Slide 6 preserves six native 290 by 160 pt frames covering exact and non-100% percentage spacing, standard/Windows line-height compatibility, and top/center/bottom anchors. The alternative selects captured font-scale and line-spacing-reduction cases, including centered/bottom anchors. These references use calibrated left-to-right ASCII and regular DejaVu Sans. Latin layout follows native separate-letter glyphs; standalone shaping is a separate operation. Slide 7 retains six native glyph specimens per option, comparing explicit scalar positions and painted ink dimensions; the alternative selects scaled originals. Public fitted copies are separate. Computed fit scales are not native autofit-choice claims. No general PowerPoint pixel-parity claim is made."], inputs: [.text, .sampleSize, .alternative], alternativeLabel: "Narrower columns, larger empty lines, reduced spacing"),
        .init(.listMarkers, title: "List markers and hanging indents", summary: "Explore 24 native bullet and numbering specimens, inherited choices and wrapped continuation lines, then compare two computed fitting paths.", operations: ["Presentation.init", "slides.importAll", "Presentation.registerEmbeddedFonts", "Part.dom", "Part.markDirty", "Shape.fitText", "TextFrame.fitText", "Presentation.renderSVG", "DeckExport.write"], limitations: ["The four original slides preserve independently captured source text, masters and layouts. Three master-only marker controls intentionally have no visible bullet. Character U+2022 and Arabic-period numbering use the bundled actual DejaVu regular, Serif and bold faces; explicit sizes, percentages, stored body scale and hanging indents retain their native evidence.", "Calibrated markers require ordinary left-aligned Latin body text, a printable first run, zero tracking and disabled effective kerning. Other marker forms, scripts, leading controls and invalid or threshold-crossing sizes retain the prior path. Identical bullet outlines do not establish a unique font identity. Finite glyph tolerances do not imply arbitrary-long-string or pixel parity.", "The fifth slide uses both public fit APIs on separate copies. Its computed scales are not native-selected autofit evidence. The alternative changes the hanging indent used for these copies; all 24 originals remain visible."], inputs: [.alternative], alternativeLabel: "Use the 6 pt hanging indent for computed fits"),
        .init(.textAlignment, title: "Text alignment", summary: "Compare 24 native center and right alignment specimens, then author and fit matching text with both public APIs.", operations: ["Presentation.init", "Paragraph.alignment", "TextFrame.text", "ShapeCollection.addTextBox", "TextFrame.setAutoFit", "Shape.fitText", "TextFrame.fitText", "Presentation.registerEmbeddedFonts", "Presentation.renderSVG", "DeckExport.write"], limitations: ["The first four slides preserve captured Latin bodies and frames: fractional widths, wrapping, trailing spaces, padding, actual font faces, kerning thresholds and table cells. Bundled DejaVu fonts are used. Native reference bounds cover these finite specimens, not arbitrary text or pixel parity.", "Table cells retain and diagnose ignored stored font scale. The fifth page uses public text authoring and computed fitting; it does not claim PowerPoint-selected autofit. The alternative changes only that page from center to right alignment."], inputs: [.alternative], alternativeLabel: "Right-align the computed comparison"),
        .init(.tableTransitions, title: "Border transitions", summary: "Inspect native color and width changes along table edges, then suppress a public control edge.", operations: ["SlideCollection.importAll", "TableCell.setBorder", "TableCell.border", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Four source pages retain 14 tables: 13 admitted native transition cases and one excluded colored merge with unchanged fallback. All 240 glyph traces are checked; outside captions use bundled DejaVu, so complete pages are not source-byte-identical.", "Native bounds cover opaque solid flat centered edges on unmerged LTR rectangles with agreeing neighbors and cells larger than the widest stroke. Interval tolerance .001 pt, RGB .0001; glyph trace x .025 pt, y .121 pt and size .002 pt. No outline-ink or universal table claim.", "The fifth page is a public authoring control, outside native numerical acceptance. Colored merges and colored RTL remain excluded."], inputs: [.alternative], alternativeLabel: "Suppress the upper left border donor"),
        .init(.partialTableStyles, title: "Partial table styles", summary: "Compare missing, empty and suppressed table edges, then restore a styled edge with public APIs.", operations: ["Table.setStyleDefinition", "TableStyleResolver.border", "TableCell.border", "TableCell.setBorder", "TableCell.clearBorder", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Two reference pages preserve twelve native specimens, 72 glyph traces, 49 border intervals and 15 fills. Only outside captions use bundled DejaVu Sans; complete pages are not source-byte-identical.", "Black 1 pt defaults apply only to absent effective cardinal edges in resolved custom definitions. Empty lines, noFill, unresolved references and direct overrides stay distinct. Captured joins are unmerged LTR with constant opaque solid color and width along each grid line; combined profiles remain outside this evidence.", "Glyph x tolerance is .025 pt, vertical tolerance .121 pt retains native print-grid residuals, and size tolerance is .002 pt. This is trace evidence, not outline ink or universal table parity. The third page is public authoring, outside the native numeric oracle; its alternative clears a direct left override."], inputs: [.alternative], alternativeLabel: "Restore the authored left edge to its style"),
        .init(.tableJoinProfiles, title: "Table join profiles", summary: "Inspect native RTL, two-color and merged borders, then author the same bounded profiles with public APIs.", operations: ["Table.rightToLeft", "Table.merge", "TableCell.setBorder", "Presentation.registerEmbeddedFonts", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Two reference pages retain eight entire native table specimens, 112 glyph traces and nine ordered crossings per colored case. Only outside captions use bundled DejaVu Sans; full pages are not source-byte-identical.", "Scope: single-color unmerged RTL; axis-uniform two-color unmerged LTR; single-color LTR merges with one orientation across the whole grid. Cells exceed the widest stroke; borders are opaque, solid and centered, without diagonals. Combined profiles and mixed merge orientations retain existing limitations.", "The third page is public authoring, not a native reference. The alternative changes its merge orientation. Glyph trace origins and sizes do not establish outline ink or universal table parity; custom-style default borders are demonstrated separately."], inputs: [.alternative], alternativeLabel: "Use a vertical authored merge"),
        .init(.tableDefaults, title: "Table defaults and border joins", summary: "Compare native table styles and border joins, then apply or clear a custom style with public APIs.", operations: ["Slides.importAll", "Table.styleID", "Table.setStyleDefinition", "TableCell.setBorder", "Presentation.registerEmbeddedFonts", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Three reference pages retain 12 entire native table specimens and 72 glyphs. Only outside captions use bundled DejaVu Sans; complete pages are not byte-identical to source.", "Native vectors cover finite style controls and rectangular unmerged LTR tables with cell dimensions larger than the widest stroke, opaque solid borders, no diagonals and one color across multi-cell joins. Other profiles retain existing limitations. Glyph trace origins and sizes are separate from border/fill geometry; no whole-slide or universal table parity claim.", "The fourth page uses public APIs. The alternative clears its custom applied style; imported source specimens and their missing applied styles stay unchanged."], inputs: [.alternative], alternativeLabel: "Clear the authored table style"),
        .init(.mixedFaceSpacing, title: "Mixed faces and exact spacing", summary: "Compare 12 native mixed-face spacing specimens and both public fitting APIs in compact frames.", operations: ["Slides.importAll", "Part.dom", "Part.markDirty", "XML.Element.children", "ShapeCollection.addShape", "TextFrame.verticalAnchor", "Shape.fitText", "TextFrame.fitText", "Presentation.registerEmbeddedFonts", "RichTextLayout.init", "Presentation.renderSVG", "DeckExport.write"], limitations: ["The two reference pages preserve all 12 native specimen nodes and frames. Only outside-frame captions change to bundled DejaVu Sans; full pages are not byte-identical to source. Exact actual per-run Sans and Serif resources are retained.", "This native extension requires distinct actual faces with equal normalized Windows vertical metrics, shape context, exact point spacing, compatible spacing and zero reduction. Unequal metrics, mixed-face percentage spacing, table contexts and rejected paint profiles retain their existing limitations. No universal mixed-font or pixel parity claim.", "The alternative moves only the computed 40 pt copies from top to bottom anchoring. Both public APIs compute 100% scale and zero reduction; these are computed fits, not PowerPoint-selected autofit."], inputs: [.alternative], alternativeLabel: "Bottom-anchor the computed copies"),
        .init(.tabLayout, title: "Tab stops and justified fields", summary: "Align numeric fields to visible left, center, right and decimal stops, then compare tab-aware Latin justification.", operations: ["Paragraph.tabStops", "Paragraph.defaultTabInterval", "Paragraph.alignment", "Paragraph.addRun", "RichTextLayout.init", "TableCell.textFrame", "Presentation.embedFont", "Presentation.registerEmbeddedFonts", "Presentation.renderSVG", "DeckExport.write"], limitations: ["Bounded left-to-right Latin fields use standard left, center, right and period-decimal stops. Locale-specific decimal separators and right-to-left tabs are not demonstrated.", "Justified wrapped lines expand ordinary spaces after the final tab; final paragraph lines retain natural spacing. Distributed and low justification remain unsupported.", "The body uses fixed English and numeric samples with bundled regular DejaVu Sans. Your text changes the title; sample size controls 2–12 rows; the alternative moves the stops. Exact saved-file positions do not establish general PowerPoint pixel parity."], inputs: [.text, .accent, .sampleSize, .alternative], alternativeLabel: "Move the tab stops right"),
        .init(.theme, title: "Theme palette and fonts", summary: "Change a theme slot and watch scheme-colored shapes resolve to the new palette.", operations: ["Theme.setColor", "Theme.setAccent", "Theme.resolve", "Theme.majorFont", "Theme.minorFont", "Fill.themeColor"], inputs: [.text, .accent, .sampleSize, .alternative], alternativeLabel: "Tint the scheme color"),
        .init(.templates, title: "Templates and document properties", summary: "Export real POTX and PPSX variants with core, extended and typed custom properties.", operations: ["Presentation.documentKind", "Presentation.slideSize", "DocumentProperties", "DocumentProperties.setCustomValue", "Presentation.serializedData"], limitations: ["Document-kind and schema checks are not an Office interoperability certificate."], inputs: [.text, .sampleSize, .alternative], alternativeLabel: "Use a 4:3 canvas"),
        .init(.design, title: "Design system and slide builders", summary: "Run every shipped slide builder plus reusable components on a parsed design system.", operations: ["Design.parse", "Presentation.applyDesign", "DeckStyle", "Grid.cell", "Rect.split", "Color.bestTextColor", "titleSlide", "sectionSlide", "closingSlide", "bulletSlide", "twoColumnSlide", "comparisonSlide", "processSlide", "pyramidSlide", "smartArtSlide", "bandsSlide", "metricsSlide", "chartSlide", "calloutSlide", "quoteSlide", "timelineSlide", "quadrantSlide", "statementSlide", "calloutBandSlide", "tableSlide", "addText", "addParagraphs", "addBulletList", "addKicker", "addStatTile", "addAccentRule", "addCard", "addButton", "addChip", "sideImagePanel"], limitations: ["Builder capacities deliberately cap dense input; this recipe records the actual retained counts.", "SmartArt is packaged as editable diagram data; SVG preview fidelity is limited.", "Design spacing/type tokens are in-memory authoring inputs; their emitted geometry and text survive reopening."], inputs: [.text, .accent, .sampleSize, .alternative], alternativeLabel: "Use a dark design"),
        .init(.mediaAndAttachments, title: "Media and foreign shape taxonomy", summary: "Embed valid owned audio/video, export their bytes, and inspect preserved group, connector and OLE XML.", operations: ["ShapeCollection.addMedia", "Picture.mediaData", "Picture.isAudio", "GroupShape.shapes", "GroupShape.convertToParentSpace", "Connector.startConnection", "GraphicFrame.graphicData", "Part.replaceBlob", "DeckExport.write"], limitations: ["SVG shows media posters, not playback; no animation is authored.", "Group, connector and OLE examples use owned low-level XML to demonstrate reading/preservation, not nonexistent high-level authoring APIs.", "The OLE frame carries an owned spreadsheet package; embedded-object activation is not implemented."], inputs: [.text, .alternative], alternativeLabel: "Omit the explicit video poster"),
        .init(.package, title: "ZIP, XML and package inspection", summary: "Inspect a bounded lazy OPC archive, demonstrate cache hits, promote it for editing, and preserve an unknown extension.", operations: ["OPCArchive.init", "OPCArchive.data(forPart:)", "OPCArchive.xml(forPart:)", "OPCArchive.clearCache", "OPCArchive.presentation", "OPCPackage.addPart", "Relationships.add", "ZipReader", "XML.parse", "Presentation.validate"], limitations: ["Validation checks required attributes; it is not complete XSD or Office conformance validation."], inputs: [.text, .sampleSize, .alternative], alternativeLabel: "Validate payloads on access"),
        .init(.extractionAndRendering, title: "Extraction and honest previews", summary: "Extract Markdown, images and chart CSV, and compare ordinary, strict and notes SVG rendering.", operations: ["Presentation.outline", "DeckOutline.markdown", "DeckExport.write", "Presentation.renderSVG", "Presentation.renderSVGReportingProblems", "Presentation.renderNotesSVGReportingProblems", "FontLibrary.previewFallbackFamily"], limitations: ["Strict rendering refuses detected unsupported content; an empty report is not a universal fidelity guarantee.", "The diagnostic slide intentionally uses a missing font measured and drawn with an explicit registered fallback, or unsupported bidirectional geometry. Substitution remains a fidelity issue."], inputs: [.text, .sampleSize, .alternative], alternativeLabel: "Use a bidirectional diagnostic sample")
    ]

    static func make(_ id: LibraryDemoID, options: LibraryLabOptions) throws -> LibraryLabDraft {
        guard (2...12).contains(options.sampleSize), Color(validating: options.accentHex) != nil else {
            throw RostrumError.packageInvalid("Library Lab expects a sample size from 2 to 12 and a six-digit accent color")
        }
        switch id {
        case .imageOwners: return try imageOwners(options)
        case .layouts: return try layouts(options)
        case .fontsAndFitting: return try fonts(options)
        case .paragraphLayout: return try paragraphLayout(options)
        case .listMarkers: return try listMarkers(options)
        case .textAlignment: return try textAlignment(options)
        case .tableTransitions: return try tableTransitions(options)
        case .partialTableStyles: return try partialTableStyles(options)
        case .tableJoinProfiles: return try tableJoinProfiles(options)
        case .tableDefaults: return try tableDefaults(options)
        case .mixedFaceSpacing: return try mixedFaceSpacing(options)
        case .tabLayout: return try tabLayout(options)
        case .theme: return try theme(options)
        case .templates: return try templates(options)
        case .design: return try design(options)
        case .mediaAndAttachments: return try media(options)
        case .package: return try package(options)
        case .extractionAndRendering: return try extraction(options)
        default: throw RostrumError.packageInvalid("Not a platform recipe: \(id.rawValue)")
        }
    }

    static func require<T>(_ value: T?, _ message: String) throws -> T {
        guard let value else { throw RostrumError.packageInvalid(message) }
        return value
    }
    static func resource(_ name: String, _ ext: String) throws -> Data {
        let url = try require(Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "LibraryLab"), "Missing bundled Library Lab resource: \(name).\(ext)")
        return try Data(contentsOf: url)
    }
    static func label(_ options: LibraryLabOptions) -> String {
        let value = String(options.text.prefix(120))
        return value.isEmpty ? "Library Lab" : value
    }
    @discardableResult
    static func text(_ value: String, on slide: Slide, in frame: Rect = LibraryLabSupport.frame(0.6, 0.5, 11, 1), font: String = "DejaVu Sans") throws -> Shape {
        let box = try slide.shapes.addTextBox(frame)
        box.textFrame?.text = value
        for paragraph in box.textFrame?.paragraphs ?? [] {
            for run in paragraph.runs { run.fontName = font; run.fontSize = 24 }
        }
        return box
    }
    static func exportedFiles(_ deck: Presentation) throws -> (files: [String: Data], assets: Int, charts: Int) {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("PlatformLab-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let summary = try DeckExport.write(deck, to: directory, named: "library-lab")
        var files: [String: Data] = [:]
        let paths = try require(FileManager.default.enumerator(at: directory, includingPropertiesForKeys: [.isRegularFileKey]), "Cannot enumerate owned extraction directory")
        for case let url as URL in paths {
            if try url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true {
                let rootPath = directory.resolvingSymlinksInPath().path + "/"
                let filePath = url.resolvingSymlinksInPath().path
                guard filePath.hasPrefix(rootPath) else { throw RostrumError.packageInvalid("Extraction escaped its owned directory") }
                files["extraction-" + String(filePath.dropFirst(rootPath.count)).replacingOccurrences(of: "/", with: "--")] = try Data(contentsOf: url)
            }
        }
        return (files, summary.assetsWritten, summary.chartsWritten)
    }
}
