#!/usr/bin/env python3
"""Independent fixture author. Requires the pinned python-pptx 1.0.2 test oracle."""
import argparse, hashlib, json, re
from pathlib import Path
import pptx
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.oxml.xmlchemy import OxmlElement

assert pptx.__version__ == '1.0.2', 'fixture producer version changed; review and repin'
root = Path(__file__).resolve().parents[2] / 'Tests/RostrumTests/Fixtures/Conformance'
root.mkdir(exist_ok=True)
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--id', default='python-tables-v2', help='new fixture ID; existing fixtures are never overwritten')
args = parser.parse_args()
if not re.fullmatch(r'[a-z0-9-]+', args.id): parser.error('fixture ID must use lowercase letters, digits and hyphens')
path = root / (args.id + '.pptx')
manifest_path = root / 'manifest.json'
manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {'schema': 1, 'fixtures': []}
if path.exists() or any(item['id'] == args.id for item in manifest['fixtures']):
    parser.error('fixture already exists; use a new ID and retain the original reference')
p = Presentation()
p.slide_width, p.slide_height = Inches(12), Inches(7)
s = p.slides.add_slide(p.slide_layouts[6])
t = s.shapes.add_table(4, 4, Inches(1), Inches(1), Inches(10), Inches(5)).table
for r in range(4):
    for c in range(4):
        cell = t.cell(r, c)
        cell.text = f'R{r} C{c}'
        cell.margin_left, cell.margin_right = Inches(.11), Inches(.23)
        cell.margin_top, cell.margin_bottom = Inches(.07), Inches(.13)
        cell.fill.solid()
        cell.fill.fore_color.rgb = RGBColor(235, 242, 250) if r % 2 else RGBColor(255, 255, 255)
        pr = cell._tc.get_or_add_tcPr()
        for index, (name, color) in enumerate([('lnL','1B365D'), ('lnR','18A999'), ('lnT','CC3300'), ('lnB','333333')]):
            line = OxmlElement('a:' + name); line.set('w', '25400')
            fill = OxmlElement('a:solidFill'); rgb = OxmlElement('a:srgbClr'); rgb.set('val',color)
            fill.append(rgb); line.append(fill); pr.insert(index,line)
t.cell(0, 0).merge(t.cell(1, 1))
t.cell(0, 0).text = 'Merged origin'
para = t.cell(2, 1).text_frame.paragraphs[0]
para.clear()
for text, bold, size in [('Mixed ',False,18), ('bold',True,24), (' text',False,14)]:
    run = para.add_run(); run.text = text
    run.font.name = 'Arial'; run.font.bold = bold; run.font.size = Pt(size)
t.columns[0].width = Inches(3); t.columns[1].width = Inches(2)
s.notes_slide.notes_text_frame.text = 'Independent table fixture notes.'
p.save(path)
manifest['fixtures'].append({
    'id': args.id, 'file': path.name, 'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
    'producer': 'python-pptx 1.0.2', 'provenance': 'Generated by Tools/conformance/make_table_fixture.py; original project test content; CC0.',
    'features': ['2x2 merge','unequal columns','explicit edge borders','asymmetric margins','mixed runs','native style ID','speaker notes'],
    'fonts': ['Arial'], 'semanticOracle': 'python-pptx 1.0.2',
    'powerPointReference': None, 'notesPageReference': None,
    'referenceStatus': 'pending Office export; release gate rejects missing reference'
  })
manifest_path.write_text(json.dumps(manifest,indent=2)+'\n')
