#!/bin/bash
# project.yml is authoritative, including when a generated project already exists.
set -euo pipefail
cd "$(dirname "$0")/.."
command -v xcodegen >/dev/null 2>&1 || {
  echo "error: Lectern.xcodeproj is generated by xcodegen; install it with: brew install xcodegen" >&2
  exit 1
}
xcodegen generate --quiet
