#!/usr/bin/env python3
"""Generate the Foundation-only native table-style catalog from pinned data.

Run from any directory. No downloads or third-party Python modules are needed.
The style definitions are PowerPoint output collected by PPTX Studio; the
adjacent LICENSE/NOTICE and THIRD_PARTY_LICENSES.md preserve attribution.
"""
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
source = json.loads((HERE / "styles.json").read_text())
styles = source["styles"]
assert len(styles) == 74
assert len({s["id"] for s in styles}) == len(styles)
assert len({s["key"] for s in styles}) == len(styles)
namespace = "http://schemas.openxmlformats.org/drawingml/2006/main"
for style in styles:
    assert re.fullmatch(r"\{[0-9A-F]{8}(?:-[0-9A-F]{4}){3}-[0-9A-F]{12}\}", style["id"])
    assert re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", style["key"])
    xml = style["xml"].replace("<a:tblStyle ", f'<a:tblStyle xmlns:a="{namespace}" ', 1)
    element = ET.fromstring(xml)
    assert element.tag == "{" + namespace + "}tblStyle"
    assert element.attrib["styleId"] == style["id"]
    assert element.attrib["styleName"] == style["name"]
    style["xml"] = xml
    style["case"] = style["key"][0].lower() + style["key"][1:]

lines = [
    "// Generated by Tools/table-style-catalog/generate.py. Do not edit by hand.",
    "// PowerPoint style data from PPTX Studio, Copyright 2026 Dewiride Technologies.",
    "// Apache-2.0; see THIRD_PARTY_LICENSES.md and Tools/table-style-catalog/NOTICE.",
    "// Source revision: " + source["source"]["revision"],
    "// Source SHA-256: " + source["source"]["sha256"],
    "import Foundation", "",
    "/// The 74 native PowerPoint table styles. Names are stable English gallery names.",
    "/// Theme colors/fonts and table header/banding flags determine their appearance.",
    "public enum BuiltInTableStyle: String, CaseIterable, Sendable {",
]
for style in styles:
    lines.append(f'    case {style["case"]} = "{style["id"]}"')
lines += [
    "", "    /// Resolve a native GUID case-insensitively, allowing surrounding XML whitespace.",
    "    public init?(id: String) {",
    "        self.init(rawValue: id.trimmingCharacters(in: .whitespacesAndNewlines).uppercased())",
    "    }", "", "    public var name: String {", "        switch self {",
]
for style in styles:
    lines.append(f'        case .{style["case"]}: return {json.dumps(style["name"])}')
lines += ["        }", "    }", "", "    // Each resolver gets its own mutable tree. No global DOM cache is shared.",
          "    func definition() -> XML.Element? { try? XML.parse(Data(definitionXML.utf8)) }", "",
          "    private var definitionXML: String {", "        switch self {"]
for style in styles:
    lines.append(f'        case .{style["case"]}: return #"{style["xml"]}"#')
lines += ["        }", "    }", "}", "", "public extension Table {",
          "    /// The referenced native style, or nil for a custom, inline or absent style.",
          "    var builtInStyle: BuiltInTableStyle? {",
          "        guard tbl.firstChild(named: \"a:tblPr\")?.firstChild(named: \"a:tableStyle\") == nil else { return nil }",
          "        return styleID.flatMap(BuiltInTableStyle.init(id:))", "    }", "",
          "    /// Change the style reference while keeping the authored header/banding flags.",
          "    @discardableResult", "    func applyBuiltInStyle(_ style: BuiltInTableStyle) -> Table {",
          "        styleID = style.rawValue", "        return self", "    }", "}", ""]
(ROOT / "Sources/Rostrum/Presentation/BuiltInTableStyle.swift").write_text("\n".join(lines))
