// FlexDeck — a deck about Rostrum, generated by Rostrum, where every slide
// exercises a different capability. Run:  swift run FlexDeck out.pptx [waves.png]
import Foundation
import Rostrum

// MARK: - Design system

enum Ink {
    static let charcoal = Color("0E1116")
    static let lift = Color("1A222E")
    static let orange = Color("F05138")   // Swift orange
    static let amber = Color("FFB454")
    static let teal = Color("18A999")
    static let ice = Color("AFC3D4")
    static let paper = Color("F5F2EC")
    static let navy = Color("16283C")
    static let ink = Color("232B36")
    static let inkSoft = Color("5A6B7A")
}

let display = "Avenir Next"
let W = 13.333333, H = 7.5

func r(_ x: Double, _ y: Double, _ w: Double, _ h: Double) -> Rect {
    Rect(x: .inches(x), y: .inches(y), width: .inches(w), height: .inches(h))
}

struct T {
    var s: String
    var size: Double
    var bold = false
    var color = Color.white
    var tracking: Double? = nil
    var spaceBefore: Double = 0
}

@discardableResult
func text(_ slide: Slide, _ frame: Rect, _ specs: [T],
          align: TextAlignment = .left, anchor: VerticalAnchor = .top,
          lineSpacing: Double = 1.0) throws -> Shape {
    let box = try slide.shapes.addTextBox(frame)
    let tf = box.textFrame!
    tf.setMargins(left: .zero, top: .zero, right: .zero, bottom: .zero)
    tf.verticalAnchor = anchor
    tf.clear()
    for spec in specs {
        let p = tf.addParagraph()
        p.alignment = align
        p.setLineSpacing(lineSpacing)
        if spec.spaceBefore > 0 { p.setSpacing(beforePoints: spec.spaceBefore) }
        let run = p.addRun(spec.s)
        run.fontName = display
        run.fontSize = spec.size
        run.bold = spec.bold
        run.color = spec.color
        if let t = spec.tracking { run.letterSpacing = t }
    }
    return box
}

func kicker(_ s: String, color: Color = Ink.orange) -> T {
    T(s: s.uppercased(), size: 14, bold: true, color: color, tracking: 3)
}

func chartTitle(_ slide: Slide, _ kickerText: String, _ title: String) throws {
    try text(slide, r(0.9, 0.55, 11.5, 0.45), [kicker(kickerText)])
    try text(slide, r(0.9, 1.0, 11.5, 0.85),
             [T(s: title, size: 34, bold: true, color: Ink.ink)])
}

/// Interpolate between palette stops (0…1 → orange → amber → teal).
func blend(_ t: Double) -> Color {
    func hex(_ c: Color) -> (Double, Double, Double) {
        let v = Int(c.hex, radix: 16)!
        return (Double((v >> 16) & 0xFF), Double((v >> 8) & 0xFF), Double(v & 0xFF))
    }
    let stops = [hex(Ink.orange), hex(Ink.amber), hex(Ink.teal)]
    let x = min(max(t, 0), 1) * 2
    let i = min(Int(x), 1)
    let f = x - Double(i)
    let (a, b) = (stops[i], stops[i + 1])
    return Color(red: Int(a.0 + (b.0 - a.0) * f),
                 green: Int(a.1 + (b.1 - a.1) * f),
                 blue: Int(a.2 + (b.2 - a.2) * f))
}

// MARK: - Build

let deck = try Presentation()
while deck.slides.count > 0 { try deck.slides.remove(at: 0) }
@MainActor func darkSlide() throws -> Slide {
    let s = try deck.slides.add(layout: deck.layout(type: "blank")!)
    try s.setBackground(.solid(Ink.charcoal))
    return s
}
@MainActor func paperSlide() throws -> Slide {
    let s = try deck.slides.add(layout: deck.layout(type: "blank")!)
    try s.setBackground(.solid(Ink.paper))
    return s
}

// ---- 1 · Title (+ live comment thread, speaker notes)
do {
    let s = try deck.slides.add(layout: deck.layout(type: "blank")!)
    try s.setBackground(.gradient(GradientFill(stops: [
        GradientStop(position: 0, color: Ink.charcoal),
        GradientStop(position: 1, color: Ink.navy),
    ], angleDegrees: 115)))
    try s.shapes.addShape(.rectangle, frame: r(0, 5.45, W, 0.055),
        fill: .gradient(GradientFill(stops: [
            GradientStop(position: 0, color: Ink.teal),
            GradientStop(position: 0.5, color: Ink.amber),
            GradientStop(position: 1, color: Ink.orange),
        ], angleDegrees: 0)))
    try text(s, r(1.0, 1.5, 11.0, 0.5), [kicker("A deck about the library that made it")])
    try text(s, r(1.0, 2.0, 11.5, 2.4), [
        T(s: "Rostrum", size: 110, bold: true),
    ])
    try text(s, r(1.0, 4.35, 11.0, 0.8), [
        T(s: "Presentations. Pure Swift. All the way down.", size: 24, color: Ink.ice),
    ])
    try text(s, r(1.0, 5.75, 11.0, 1.2), [
        T(s: "Every slide in this deck exercises a different subsystem —", size: 15, color: Ink.ice),
        T(s: "layouts, SmartArt, native charts, tables, pictures, comments, notes.", size: 15, color: Ink.inkSoft),
    ], lineSpacing: 1.25)
    try s.setNotes("This deck is self-referential on purpose: the file you are presenting was emitted by the library it describes. Check the comment thread on this slide.")
    let c = try s.addComment("Deck about the library, by the library. Too meta?", author: "Claude Fable", at: (x: .inches(1), y: .inches(2)))
    try c.addReply("Exactly meta enough. Ship it.", author: "Rostrum CI")
}

// ---- 2 · Placeholder-driven slide (Title and Content layout, geometry inherited)
do {
    let s = try deck.slides.add(layout: deck.layout(type: "obj")!)
    s.title?.textFrame.map { tf in
        tf.clear()
        let p = tf.addParagraph()
        let run = p.addRun("This slide owns no geometry")
        run.fontName = display; run.fontSize = 34; run.bold = true; run.color = Ink.ink
    }
    if let body = s.placeholder(idx: 1)?.textFrame {
        body.clear()
        for line in [
            "Title and body are placeholders cloned from the layout — position and size resolve",
            "through the inheritance chain: slide → layout → master.",
        ] {
            let p = body.addParagraph()
            p.setLineSpacing(1.25)
            let run = p.addRun(line)
            run.fontName = display; run.fontSize = 19; run.color = Ink.inkSoft
        }
        let code = body.addParagraph()
        code.setSpacing(beforePoints: 14)
        let codeRun = code.addRun("slides.add(layout: deck.layout(type: \"obj\")!)")
        codeRun.fontName = "Menlo"; codeRun.fontSize = 16; codeRun.color = Ink.teal
    }
    try s.setNotes("Placeholder inheritance: the sp elements carry only a ph binding; renderers pull geometry from the layout and master.")
}

// ---- 3 · Architecture SmartArt
do {
    let s = try darkSlide()
    try text(s, r(0.9, 0.55, 11.5, 0.45), [kicker("The stack", color: Ink.teal)])
    try text(s, r(0.9, 1.0, 11.5, 0.8), [T(s: "Five layers, zero dependencies", size: 34, bold: true)])
    try s.shapes.addSmartArt(items: [
        "Zip — bytes, CRC-32, pure-Swift DEFLATE",
        "XML — prefix-faithful DOM, deterministic serializer",
        "OPC — parts, content types, relationship graph",
        "Schema — tables generated from python-pptx itself",
        "API — slides, shapes, text, charts, diagrams",
    ], frame: r(2.9, 1.95, 7.5, 5.1),
       colors: (0..<5).map { blend(Double($0) / 4) })
    try s.setNotes("This SmartArt is a real DrawingML diagram: data, layout, quickStyle and colors parts, using Rostrum's own verified layout definition. Click into it in PowerPoint — it is editable.")
}

// ---- 4 · Big numbers
do {
    let s = try darkSlide()
    try text(s, r(0.9, 0.55, 11.5, 0.45), [kicker("Today, measured")])
    try text(s, r(0.9, 1.0, 11.5, 0.85),
             [T(s: "A one-hour ledger", size: 34, bold: true)])
    let stats: [(String, String, Color)] = [
        ("180", "tests, all green, every commit", Ink.teal),
        ("0", "dependencies, end to end", Ink.amber),
        ("11", "commits in sixty minutes", Ink.orange),
    ]
    let cw = 3.7, gap = 0.35
    for (i, stat) in stats.enumerated() {
        let x = 0.95 + Double(i) * (cw + gap)
        try s.shapes.addShape(.rectangle, frame: r(x, 2.1, 0.07, 2.9), fill: .solid(stat.2))
        try text(s, r(x + 0.3, 2.05, cw - 0.4, 2.0),
                 [T(s: stat.0, size: 110, bold: true, color: stat.2)])
        try text(s, r(x + 0.32, 4.35, cw - 0.4, 0.9),
                 [T(s: stat.1, size: 17, color: Ink.ice)], lineSpacing: 1.15)
    }
    try s.setNotes("All three numbers are measured from the repository at generation time, not typed in.")
}

// ---- 5 · Line chart: test growth
do {
    let s = try paperSlide()
    try chartTitle(s, "swift test, per commit", "One hour of test growth")
    try s.shapes.addChart(.line,
        data: ChartData(categories: ["11:57", "12:00", "12:13", "12:20", "12:32", "12:35", "12:39", "12:45", "12:47", "12:55", "12:57"],
                        series: [.init(name: "Tests passing", values: [116, 121, 135, 136, 148, 152, 157, 162, 167, 171, 180])]),
        frame: r(0.9, 1.85, 11.5, 5.1),
        colors: [Ink.orange])
    try s.setNotes("Native c: chart with an embedded Edit-Data workbook — right-click, Edit Data, and Excel opens a sheet Rostrum's own zip writer produced.")
}

// ---- 6 · Bar chart: code by layer
do {
    let s = try paperSlide()
    try chartTitle(s, "wc -l, by directory", "Where the Swift lives")
    try s.shapes.addChart(.barClustered,
        data: ChartData(categories: ["API", "Schema", "Zip", "Charts", "OPC", "XML", "Drawing", "Core"],
                        series: [.init(name: "Lines of Swift", values: [2023, 1461, 768, 532, 467, 349, 270, 85])]),
        frame: r(0.9, 1.85, 11.5, 5.1),
        colors: [Ink.teal])
    try s.setNotes("5,955 lines of library source plus 2,755 lines of tests. The Schema layer is mostly generated by rostrum-gen from python-pptx's own declaration tables.")
}

// ---- 7 · Pie chart: test taxonomy
do {
    let s = try paperSlide()
    try chartTitle(s, "180 tests, by subject", "What the suite defends")
    let slices: [(String, Double, Color)] = [
        ("Container — zip · DEFLATE · CRC", 51, Ink.orange),
        ("XML fidelity", 37, Ink.amber),
        ("Feature suites", 30, Ink.teal),
        ("Object model", 29, Color("5B9BD5")),
        ("Guardrails & regressions", 19, Ink.ice),
        ("OPC packaging", 14, Color("8A9BAE")),
    ]
    try s.shapes.addChart(.pie,
        data: ChartData(categories: slices.map(\.0), name: "Tests",
                        values: slices.map(\.1)),
        frame: r(0.7, 1.75, 6.3, 5.4),
        colors: slices.map(\.2))
    // Hand-built legend: chip + label + count, aligned right of the pie.
    for (i, slice) in slices.enumerated() {
        let y = 2.75 + Double(i) * 0.62
        try s.shapes.addShape(.roundedRectangle, frame: r(7.5, y + 0.04, 0.3, 0.3),
                              fill: .solid(slice.2))
        try text(s, r(7.95, y, 3.9, 0.5),
                 [T(s: slice.0, size: 15, color: Ink.ink)])
        try text(s, r(11.9, y, 0.6, 0.5),
                 [T(s: String(Int(slice.1)), size: 15, bold: true, color: Ink.inkSoft)], align: .right)
    }
    try s.setNotes("Slices sum to exactly 180 — counted from swift test list at generation time. The legend is shape-built; the pie is a native chart.")
}

// ---- 8 · Parity table
do {
    let s = try paperSlide()
    try chartTitle(s, "measured against the original", "Feature parity — and past it")
    let t = try s.shapes.addTable(rows: 7, columns: 3, frame: r(0.9, 1.9, 11.5, 4.6))
    t.setColumnWidth(0, .inches(6.1))
    t.setColumnWidth(1, .inches(2.7))
    t.setColumnWidth(2, .inches(2.7))
    let rows: [(String, String, String)] = [
        ("Capability", "Rostrum", "python-pptx"),
        ("Slide remove · move · duplicate", "✓", "—"),
        ("Modern threaded comments", "✓", "—"),
        ("SmartArt: create and read", "✓", "—"),
        ("Untouched parts byte-identical on save", "✓", "—"),
        ("Native charts with Edit-Data workbook", "✓", "✓"),
        ("Speaker notes, pictures, tables", "✓", "✓"),
    ]
    for (ri, row) in rows.enumerated() {
        for (ci, value) in [row.0, row.1, row.2].enumerated() {
            let cell = t.cell(ri, ci)
            cell.verticalAnchor = .middle
            let tf = cell.textFrame
            tf.clear()
            let p = tf.addParagraph()
            if ci > 0 { p.alignment = .center }
            let run = p.addRun(value)
            run.fontName = display
            run.fontSize = ri == 0 ? 17 : 16
            run.bold = ri == 0 || ci == 1
            run.color = ri == 0 ? .white : (ci == 1 ? Ink.teal : Ink.inkSoft)
            if ri == 0 { cell.setFill(.solid(Ink.navy)) }
        }
    }
    try s.setNotes("The dashes are python-pptx's 15-year-old open feature requests.")
}

// ---- 9 · Generative shape art
do {
    let s = try darkSlide()
    let cols = 16, rowsN = 6
    let cell = W / Double(cols)
    let geometries: [ShapeGeometry] = [.roundedRectangle, .ellipse, .triangle]
    for row in 0..<rowsN {
        for col in 0..<cols {
            let t = Double(col) / Double(cols - 1)
            let inset = 0.16
            let shape = try s.shapes.addShape(
                geometries[(row + col) % geometries.count],
                frame: r(Double(col) * cell + inset, 0.55 + Double(row) * cell + inset,
                         cell - 2 * inset, cell - 2 * inset),
                fill: .solidAlpha(blend(t), 0.25 + 0.65 * Double(row) / Double(rowsN - 1)))
            shape.rotation = Double((row * 37 + col * 23) % 360)
        }
    }
    try s.shapes.addShape(.rectangle, frame: r(0, 5.75, W, 1.75),
        fill: .gradient(GradientFill(stops: [
            GradientStop(position: 0, color: Ink.charcoal, alpha: 0),
            GradientStop(position: 1, color: Ink.charcoal, alpha: 0.95),
        ], angleDegrees: 90)))
    try text(s, r(0.9, 6.1, 11.5, 0.7),
             [T(s: "96 shapes, 3 geometries, EMU-exact", size: 30, bold: true)])
    try text(s, r(0.9, 6.8, 11.5, 0.45),
             [T(s: "Preset geometry · rotation · alpha — generated in a loop, placed to the EMU", size: 15, color: Ink.ice)])
    try s.setNotes("Every tile is an autoshape with computed fill, alpha and rotation — the kind of parametric design a code-first library makes trivial.")
}

// ---- 10 · Picture slide
do {
    let waveData = wavesPNG
    let s = try darkSlide()
    try text(s, r(0.9, 0.55, 11.5, 0.45), [kicker("Pictures", color: Ink.amber)])
    try text(s, r(0.9, 1.0, 11.5, 0.8),
             [T(s: "One PNG, two placements, one media part", size: 34, bold: true)])
    try s.shapes.addPicture(waveData, frame: r(0.9, 2.05, 8.0, 4.5))
    try s.shapes.addPicture(waveData, frame: r(9.3, 2.05, 3.1, 1.74))
    try text(s, r(9.3, 4.0, 3.1, 2.5), [
        T(s: "Identical bytes deduplicate to a single /ppt/media part.", size: 14, color: Ink.ice),
        T(s: "Dimensions and dpi sniffed by pure-Swift header parsers.", size: 14, color: Ink.inkSoft, spaceBefore: 8),
    ], lineSpacing: 1.2)
    try s.setNotes("The image itself was generated programmatically — layered sine waves in the deck palette.")
}

// ---- 11 · Divider (Section Header layout, real placeholders)
do {
    let s = try deck.slides.add(layout: deck.layout(type: "secHead")!)
    try s.setBackground(.gradient(GradientFill(
        from: Ink.navy, to: Ink.charcoal, angleDegrees: 115)))
    let ghost = try s.shapes.addTextBox(r(6.2, 0.7, 6.8, 6.1))
    ghost.textFrame.map { tf in
        tf.verticalAnchor = .middle
        tf.clear()
        let p = tf.addParagraph()
        p.alignment = .right
        let run = p.addRun("03")
        run.fontName = display; run.fontSize = 300; run.bold = true; run.color = Ink.lift
    }
    s.title?.textFrame.map { tf in
        tf.clear()
        let p = tf.addParagraph()
        let run = p.addRun("What\u{2019}s next")
        run.fontName = display; run.fontSize = 60; run.bold = true; run.color = .white
    }
    if let body = s.placeholder(idx: 1) {
        // Materialize a narrower frame so the text clears the ghost numeral
        // (which, added after the placeholders, paints above them).
        body.frame = Rect(x: EMU(831_850), y: .inches(4.45),
                          width: .inches(5.1), height: .inches(1.4))
        if let tf = body.textFrame {
            tf.clear()
            let p = tf.addParagraph()
            p.setLineSpacing(1.2)
            let run = p.addRun("Three features on deck — ranked by unanswered demand")
            run.fontName = display; run.fontSize = 18; run.color = Ink.ice
        }
    }
    try s.setNotes("This divider uses the real Section Header layout — title and body are placeholders, the ghost numeral is a plain text box.")
}

// ---- 12 · Roadmap cards
do {
    let s = try paperSlide()
    try text(s, r(0.9, 0.55, 11.5, 0.45), [kicker("The roadmap")])
    try text(s, r(0.9, 1.0, 11.5, 0.8),
             [T(s: "Next muscles to grow", size: 34, bold: true, color: Ink.ink)])
    let cards: [(String, String, String)] = [
        ("🔀", "Deck merge", "Copy a slide between decks with images, charts and rels intact — the #1 unsolved workflow."),
        ("🎨", "Brand kit", "A real Theme object: palette, fonts, apply-a-brand — and schemeClr→RGB resolution."),
        ("🖼️", "Rendering", "Slide → image/PDF without LibreOffice. The moonshot."),
    ]
    let cw = (W - 2 * 0.9 - 2 * 0.35) / 3, gap = 0.35
    for (i, card) in cards.enumerated() {
        let x = 0.9 + Double(i) * (cw + gap)
        let panel = try s.shapes.addShape(.roundedRectangle, frame: r(x, 2.25, cw, 3.9), fill: .solid(.white))
        panel.enableSoftShadow()
        try text(s, r(x + 0.3, 2.55, cw - 0.6, 0.8), [T(s: card.0, size: 40)])
        try text(s, r(x + 0.3, 3.5, cw - 0.6, 0.5),
                 [T(s: card.1, size: 21, bold: true, color: Ink.ink)])
        try text(s, r(x + 0.3, 4.1, cw - 0.6, 1.8),
                 [T(s: card.2, size: 14.5, color: Ink.inkSoft)], lineSpacing: 1.25)
    }
    try s.setNotes("Ranked by demand evidence in python-pptx's issue tracker, per the research pass in ROADMAP.md.")
}

// ---- 13 · Closing (+ resolved comment)
do {
    let s = try darkSlide()
    try s.shapes.addShape(.rectangle, frame: r(0, 3.58, W, 0.05),
        fill: .gradient(GradientFill(stops: [
            GradientStop(position: 0, color: Ink.orange),
            GradientStop(position: 0.5, color: Ink.amber),
            GradientStop(position: 1, color: Ink.teal),
        ], angleDegrees: 0)))
    try text(s, r(1.0, 2.3, 11.4, 1.1),
             [T(s: "Made of Swift. All the way down.", size: 50, bold: true)], align: .center)
    try text(s, r(1.0, 3.95, 11.4, 0.6),
             [T(s: "github.com/welshofer/rostrum", size: 20, color: Ink.amber, tracking: 1)], align: .center)
    try text(s, r(1.0, 6.6, 11.4, 0.6), [
        T(s: "Deck, charts, diagrams, workbooks and this sentence: emitted by Rostrum · zero dependencies", size: 13, color: Ink.ice),
    ], align: .center)
    let done = try s.addComment("Reviewed every slide. We're good.", author: "Rostrum CI", at: (x: .inches(11.5), y: .inches(6.5)))
    done.resolve()
    try s.setNotes("The resolved comment on this slide is real too.")
}

// MARK: - Save

let outputPath = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "flex.pptx"
try deck.save(to: URL(filePath: outputPath))
print("wrote \(outputPath): \(deck.slides.count) slides")
